// Stadium scenarios + scripted multi-agent reasoning traces.
// Each scenario carries the raw JSON telemetry + a deterministic
// "agent transcript" the simulator replays token-by-token so the
// demo feels live without a real model call.

window.SCENARIOS = {
  vip_arrival: {
    id: "SCENARIO_04",
    key: "vip_arrival",
    name: "Marquee Player Arrival · Gate 02",
    short: "VIP Arrival",
    timestamp: "19:00",
    match_status: "PRE_MATCH_VIP_INBOUND",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 180,
      gate_03_turnstile_rate_per_min: 95,
      gate_05_turnstile_rate_per_min: 130,
      concourse_b_density_index: 0.55,
      metro_station_queue_length_meters: 60,
    },
    expected_severity: "ORANGE",
    zone_state: {
      g1: "green", g2: "orange", g3: "green", g4: "green", g5: "green",
      concourse_n: "orange", concourse_s: "green",
      concourse_e: "orange", concourse_w: "green",
      metro: "green",
    },
    payload: {
      severity_level: "ORANGE",
      reasoning_justification:
        "Marquee player convoy ETA Gate-02 at T+4 min. Social-signal triangulation shows 11,300 fans converging on Concourse-E within the next 6 min window. Recommend hard-seal of VIP corridor, redirect general admission flow to West Ring, and pre-position security at G2 annex. No life-safety risk at current posture — escalates only if rain or G3 capacity drops in parallel.",
      mitigation_directives: [
        { target_zone: "Gate 02 VIP Annex", action_required: "HARD SEAL · DEPLOY 8 SECURITY UNITS", priority: "IMMEDIATE" },
        { target_zone: "Concourse E", action_required: "RESTRICT TO MEDIA PASS · MOVE GA FLOW TO W-RING", priority: "IMMEDIATE" },
        { target_zone: "North Approach", action_required: "ACTIVATE BARRIER BUFFER · STAGGER FAN APPROACH", priority: "DEFERRED" },
      ],
      pa_system_announcement_script:
        "Welcome to Chinnaswamy. Please proceed to your seats — the Gate 2 corridor is closed for player arrival. Use Gates 1, 3 or 5.\n\n[KN] ಚಿನ್ನಸ್ವಾಮಿಗೆ ಸ್ವಾಗತ. ಆಟಗಾರರ ಪ್ರವೇಶಕ್ಕಾಗಿ ಗೇಟ್ 2 ಮುಚ್ಚಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಗೇಟ್ 1, 3 ಅಥವಾ 5 ಬಳಸಿ.",
      mobile_push_notification_text:
        "Gate 2 closed for player arrival. Use Gate 1, 3 or 5 to reach your seat.",
    },
    trace: [
      { agent: "sensor", level: "info", text: "Ingesting telemetry payload SCENARIO_04 ✓ social-signal channel armed.", t: 0 },
      { agent: "sensor", level: "info", text: "VIP convoy beacon · ETA Gate-02 T+4m · 11,300 fan-mentions / min.", t: 280 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 540 },
      { agent: "dispatcher", level: "think", text: "Celebrity-proximity index 0.88 · projected Concourse-E surge in 6 min.", t: 940 },
      { agent: "dispatcher", level: "think", text: "Tool::seal_corridor(zone=G2_annex) · Tool::reroute(GA → W-Ring).", t: 1320 },
      { agent: "dispatcher", level: "warn", text: "Severity classification: ORANGE · pre-emptive seal pattern.", t: 1700 },
      { agent: "dispatcher", level: "emit", text: "Structured payload emitted · severity=ORANGE · directives=3", t: 2040 },
      { agent: "broadcast", level: "info", text: "Map: G2 → ORANGE · Concourse N/E amber · security paged.", t: 2320 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 2.8s end-to-end.", t: 2600 },
    ],
  },

  drone_airspace: {
    id: "SCENARIO_05",
    key: "drone_airspace",
    name: "Unauthorised Drone · Pitch Airspace",
    short: "Drone",
    timestamp: "20:42",
    match_status: "ACTIVE_PLAY",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 60,
      gate_03_turnstile_rate_per_min: 70,
      gate_05_turnstile_rate_per_min: 55,
      concourse_b_density_index: 0.68,
      metro_station_queue_length_meters: 30,
    },
    expected_severity: "RED",
    zone_state: {
      g1: "orange", g2: "orange", g3: "orange", g4: "orange", g5: "orange",
      concourse_n: "red", concourse_s: "red",
      concourse_e: "red", concourse_w: "red",
      metro: "orange",
    },
    payload: {
      severity_level: "RED",
      reasoning_justification:
        "Unidentified aerial vehicle detected 38m above pitch · radar cross-section consistent with sub-2kg consumer drone. BCAS protocol mandates immediate match suspension and stand-shelter posture pending payload assessment. Coordinate with Bengaluru ATC + State Police Bomb Squad. PA must instruct stand-in-place, NOT evacuate, to prevent crush from 41k seated patrons.",
      mitigation_directives: [
        { target_zone: "Pitch Airspace", action_required: "SUSPEND PLAY · GROUND STAFF & PLAYERS TO TUNNEL", priority: "IMMEDIATE" },
        { target_zone: "All Stands", action_required: "STAND-IN-PLACE ANNOUNCEMENT · DO NOT EVACUATE", priority: "IMMEDIATE" },
        { target_zone: "All Gates 01–05", action_required: "HOLD INBOUND · BUFFER QUEUES AT 50m PERIMETER", priority: "IMMEDIATE" },
        { target_zone: "Bengaluru ATC + State Police", action_required: "OPEN CHANNEL · BOMB SQUAD INBOUND", priority: "IMMEDIATE" },
        { target_zone: "Roof Cam Grid", action_required: "TRACK + LOG VEHICLE TRAJECTORY · 30FPS", priority: "DEFERRED" },
      ],
      pa_system_announcement_script:
        "Please remain in your seats. Play is briefly suspended for a safety check. Do not move from your stand. Updates in 60 seconds.\n\n[KN] ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆಸನಗಳಲ್ಲಿಯೇ ಉಳಿಯಿರಿ. ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆಗಾಗಿ ಆಟ ತಾತ್ಕಾಲಿಕವಾಗಿ ಸ್ಥಗಿತಗೊಂಡಿದೆ.",
      mobile_push_notification_text:
        "🚨 Stay seated. Play paused for safety check. Do not leave your stand. Next update in 60 sec.",
    },
    auditor: {
      verdict: "CLEARED",
      checks: [
        { label: "BCAS aerial-incursion SOP alignment", result: "Stand-in-place posture matches DGCA-BCAS § 7.3 · APPROVED" },
        { label: "PA script anti-panic review", result: "'Suspended' favored over 'evacuated' · panic-vector score 0.04" },
        { label: "Inbound-hold capacity at 50m perimeter", result: "Buffer zone supports 8,400 patrons · within margin" },
        { label: "ATC coordination handshake", result: "Channel BLR-OPS-3 acknowledged · 12s latency" },
      ],
      clearance: true,
    },
    trace: [
      { agent: "sensor", level: "alert", text: "Roof-cam radar fusion · unidentified aerial vehicle · 38m above pitch.", t: 0 },
      { agent: "sensor", level: "alert", text: "Cross-section 0.18m² · consumer-class · payload unknown.", t: 320 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 600 },
      { agent: "dispatcher", level: "think", text: "BCAS protocol trigger · suspend play · stand-shelter mode.", t: 1000 },
      { agent: "dispatcher", level: "alert", text: "Severity=RED — gating broadcast pending Auditor clearance.", t: 1380 },
      { agent: "dispatcher", level: "info", text: "Escalating → Risk Auditor Node [gemini-2.5-pro]", t: 1660 },
      { agent: "auditor", level: "info", text: "Auditor node online · 4-point aerial-incursion verification.", t: 1960 },
      { agent: "auditor", level: "think", text: "Check 1/4 · BCAS § 7.3 alignment ✓", t: 2320 },
      { agent: "auditor", level: "think", text: "Check 2/4 · PA anti-panic vector 0.04 ✓", t: 2680 },
      { agent: "auditor", level: "think", text: "Check 3/4 · 50m buffer supports 8,400 patrons ✓", t: 3040 },
      { agent: "auditor", level: "think", text: "Check 4/4 · ATC channel handshake 12s ✓", t: 3400 },
      { agent: "auditor", level: "ok", text: "auditor_clearance = TRUE · releasing payload.", t: 3760 },
      { agent: "broadcast", level: "alert", text: "Map: pitch airspace RED · all stands amber · gates held.", t: 4060 },
      { agent: "broadcast", level: "info", text: "Mobile push staged · 41,200 devices in bowl.", t: 4340 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 4.6s · auditor cleared.", t: 4620 },
    ],
  },


  baseline_exit: {
    id: "SCENARIO_01",
    key: "baseline_exit",
    name: "Standard Post-Match Exit Flow",
    short: "Baseline",
    timestamp: "22:45",
    match_status: "CONCLUDED",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 140,
      gate_03_turnstile_rate_per_min: 165,
      gate_05_turnstile_rate_per_min: 120,
      concourse_b_density_index: 0.42,
      metro_station_queue_length_meters: 45,
    },
    expected_severity: "GREEN",
    zone_state: {
      g1: "green", g2: "green", g3: "green", g4: "green", g5: "green",
      concourse_n: "green", concourse_s: "green",
      concourse_e: "green", concourse_w: "green",
      metro: "green",
    },
    payload: {
      severity_level: "GREEN",
      reasoning_justification:
        "All five turnstile gates registering nominal egress velocity within the 110–170 ppm operational band. Concourse B density holds at 0.42 — well below the 0.70 caution threshold. Metro corridor queue length is 45m, inside the comfort envelope for the 22:45 dispersal window. No mitigation required; recommend passive monitoring.",
      mitigation_directives: [
        { target_zone: "All Gates 01–05", action_required: "MAINTAIN STANDARD EGRESS CADENCE", priority: "MONITOR" },
        { target_zone: "MG Road Metro Corridor", action_required: "CONTINUE PASSIVE QUEUE SAMPLING @ 30s", priority: "MONITOR" },
      ],
      pa_system_announcement_script:
        "Thank you for joining us tonight at Chinnaswamy. Please exit via your nearest marked gate. Drive home safely.\n\n[KN] ಇಂದು ರಾತ್ರಿ ಚಿನ್ನಸ್ವಾಮಿಗೆ ಸೇರಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹತ್ತಿರದ ಗೇಟ್‌ನಿಂದ ನಿರ್ಗಮಿಸಿ.",
      mobile_push_notification_text:
        "Match concluded. Use your assigned gate for fastest exit. MG Rd Metro wait ~3 min.",
    },
    trace: [
      { agent: "sensor", level: "info", text: "Ingesting telemetry payload SCENARIO_01 ✓ 5 sensor channels parsed.", t: 0 },
      { agent: "sensor", level: "info", text: "Rainfall=0.0mm · Concourse-B density=0.42 · Metro queue=45m", t: 280 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 520 },
      { agent: "dispatcher", level: "info", text: "Model spin-up · context window primed · tools: { broadcast, route, alert }", t: 760 },
      { agent: "dispatcher", level: "think", text: "Egress rates [140, 165, 120] within nominal band. No bottleneck signature detected.", t: 1180 },
      { agent: "dispatcher", level: "think", text: "Severity classification: GREEN — passive monitoring sufficient.", t: 1620 },
      { agent: "dispatcher", level: "emit", text: "Structured payload emitted · severity=GREEN · directives=2", t: 1960 },
      { agent: "broadcast", level: "info", text: "Map state unchanged · PA script queued · mobile push staged.", t: 2240 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 2.4s end-to-end · no auditor invocation.", t: 2480 },
    ],
  },

  sudden_downpour: {
    id: "SCENARIO_02",
    key: "sudden_downpour",
    name: "Sudden Downpour at Over 38",
    short: "Downpour",
    timestamp: "21:15",
    match_status: "ACTIVE_RAIN_DELAY",
    current_rainfall_mm: 18.5,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 310,
      gate_03_turnstile_rate_per_min: 520,
      gate_05_turnstile_rate_per_min: 95,
      concourse_b_density_index: 0.91,
      metro_station_queue_length_meters: 280,
    },
    expected_severity: "ORANGE",
    zone_state: {
      g1: "orange", g2: "green", g3: "orange", g4: "green", g5: "green",
      concourse_n: "orange", concourse_s: "orange",
      concourse_e: "green", concourse_w: "orange",
      metro: "orange",
    },
    payload: {
      severity_level: "ORANGE",
      reasoning_justification:
        "Rainfall spike to 18.5mm coincides with a 215% egress surge at Gate 03 (520 ppm vs 165 baseline) and Concourse-B density at 0.91 — critical-adjacent. Gate 05 is under-utilised at 95 ppm and can absorb redirected flow. Metro queue at 280m signals downstream pressure; dispatch a hold-and-shelter pattern while opening overflow gates and rerouting via Concourse-E.",
      mitigation_directives: [
        { target_zone: "Gate 05 & Overflow Gate 06", action_required: "OPEN OVERFLOW GATES 5 & 6 · DEPLOY 4 STEWARDS", priority: "IMMEDIATE" },
        { target_zone: "Concourse B", action_required: "REROUTE 40% OF GATE-03 FLOW VIA CONCOURSE E", priority: "IMMEDIATE" },
        { target_zone: "Covered Concourse Ring", action_required: "ACTIVATE SHELTER-IN-PLACE FOR ZONES B / W", priority: "IMMEDIATE" },
        { target_zone: "MG Road Metro Corridor", action_required: "STAGGER RELEASE @ 90s INTERVALS", priority: "DEFERRED" },
      ],
      pa_system_announcement_script:
        "Attention all patrons. Heavy rainfall in progress. Please move calmly to the covered concourse and avoid Gate 3. Gates 5 and 6 are now open as overflow exits.\n\n[KN] ಎಲ್ಲಾ ಪ್ರೇಕ್ಷಕರಿಗೆ ಸೂಚನೆ. ಭಾರೀ ಮಳೆಯಿಂದಾಗಿ, ದಯವಿಟ್ಟು ಶಾಂತವಾಗಿ ಮುಚ್ಚಿದ ಕಾನ್ಕೋರ್ಸ್‌ಗೆ ತೆರಳಿ. ಗೇಟ್ 3 ಬಳಸಬೇಡಿ. ಗೇಟ್ 5 ಮತ್ತು 6 ಈಗ ತೆರೆಯಲಾಗಿದೆ.",
      mobile_push_notification_text:
        "⚠ Heavy rain. Avoid Gate 3. Overflow Gates 5 & 6 are now OPEN. Shelter in covered concourse.",
    },
    trace: [
      { agent: "sensor", level: "info", text: "Ingesting telemetry payload SCENARIO_02 ✓ 5 sensor channels parsed.", t: 0 },
      { agent: "sensor", level: "warn", text: "Δ-rainfall +18.5mm in 90s window · Gate-03 surge +215% above baseline.", t: 320 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 600 },
      { agent: "dispatcher", level: "think", text: "Cross-correlating rainfall vector with concourse density gradient...", t: 980 },
      { agent: "dispatcher", level: "think", text: "Gate-03 saturated (520 ppm) · Gate-05 capacity headroom 215 ppm.", t: 1420 },
      { agent: "dispatcher", level: "think", text: "Tool::route_flow(from=G3, to=G5+G6, fraction=0.40) — feasible.", t: 1800 },
      { agent: "dispatcher", level: "warn", text: "Severity classification: ORANGE — immediate redirect + shelter pattern.", t: 2180 },
      { agent: "dispatcher", level: "emit", text: "Structured payload emitted · severity=ORANGE · directives=4", t: 2540 },
      { agent: "broadcast", level: "info", text: "Map quadrants N/S/W shifted to ORANGE · Metro corridor amber.", t: 2820 },
      { agent: "broadcast", level: "info", text: "Mobile push staged · 12,400 devices in geo-fence radius.", t: 3100 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 3.3s end-to-end · no auditor invocation (sub-RED).", t: 3380 },
    ],
  },

  perimeter_breach: {
    id: "SCENARIO_03",
    key: "perimeter_breach",
    name: "Gate 3 Structural Bottleneck & Surge",
    short: "Breach",
    timestamp: "18:30",
    match_status: "MID_INNINGS_BREAK",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 90,
      gate_03_turnstile_rate_per_min: 680,
      gate_05_turnstile_rate_per_min: 110,
      concourse_b_density_index: 0.96,
      metro_station_queue_length_meters: 15,
    },
    expected_severity: "RED",
    zone_state: {
      g1: "green", g2: "orange", g3: "red", g4: "orange", g5: "green",
      concourse_n: "red", concourse_s: "orange",
      concourse_e: "green", concourse_w: "red",
      metro: "green",
    },
    payload: {
      severity_level: "RED",
      reasoning_justification:
        "Gate-03 turnstile rate at 680 ppm exceeds structural-safe limit (450 ppm) — consistent with a downstream perimeter obstruction creating compression wave back into Concourse-B (density 0.96, crush-adjacent). Metro queue paradoxically low (15m) confirms blockage is local to Gate-03 corridor, not downstream. Recommend immediate Gate-03 SOFT CLOSE, redirect to Gates 01/05, dispatch medical + structural inspection units. Escalate to Risk Auditor Node before broadcast.",
      mitigation_directives: [
        { target_zone: "Gate 03", action_required: "SOFT CLOSE · 60s GRACE · STRUCTURAL TEAM ON-SITE", priority: "IMMEDIATE" },
        { target_zone: "Concourse B / West Ring", action_required: "HALT INBOUND FLOW · REVERSE FOOT TRAFFIC TO E-RING", priority: "IMMEDIATE" },
        { target_zone: "Gates 01 & 05", action_required: "EXPAND ACTIVE TURNSTILE LANES +3 EACH", priority: "IMMEDIATE" },
        { target_zone: "Medical Bay 02", action_required: "PRE-POSITION 2 PARAMEDIC UNITS AT G3 PERIMETER", priority: "IMMEDIATE" },
        { target_zone: "Bengaluru Police Control", action_required: "NOTIFY SOC · OPEN BI-DIRECTIONAL CHANNEL", priority: "IMMEDIATE" },
      ],
      pa_system_announcement_script:
        "Important safety announcement. Gate 3 is temporarily closed. Please do not push. Use Gates 1 and 5 to exit. Stewards will direct you. Stay calm.\n\n[KN] ಮುಖ್ಯ ಸುರಕ್ಷತಾ ಸೂಚನೆ. ಗೇಟ್ 3 ತಾತ್ಕಾಲಿಕವಾಗಿ ಮುಚ್ಚಲಾಗಿದೆ. ದಯವಿಟ್ಟು ತಳ್ಳಬೇಡಿ. ಗೇಟ್ 1 ಮತ್ತು 5 ಮೂಲಕ ನಿರ್ಗಮಿಸಿ. ಶಾಂತವಾಗಿರಿ.",
      mobile_push_notification_text:
        "🚨 GATE 3 CLOSED — do not approach. Exit via Gate 1 or 5. Follow stewards. Stay calm.",
    },
    auditor: {
      verdict: "CLEARED",
      checks: [
        { label: "Density crush-risk model · Concourse-B", result: "0.96 → mitigated to projected 0.71 within 90s of redirect" },
        { label: "Gate-03 soft-close safety envelope", result: "60s grace window above min threshold (45s) · APPROVED" },
        { label: "Counter-flow vector on E-Ring", result: "No collision with inbound traffic · APPROVED" },
        { label: "PA script tonal review · panic-inducing terms", result: "0 flagged terms · bilingual parity confirmed" },
        { label: "Medical pre-position sufficiency", result: "2 units / 800m radius — meets BCCI cricket-day SOP" },
      ],
      clearance: true,
    },
    trace: [
      { agent: "sensor", level: "info", text: "Ingesting telemetry payload SCENARIO_03 ✓ 5 sensor channels parsed.", t: 0 },
      { agent: "sensor", level: "alert", text: "Gate-03 rate 680 ppm > structural-safe 450 ppm · BREACH FLAG.", t: 280 },
      { agent: "sensor", level: "alert", text: "Concourse-B density 0.96 — crush-adjacent. Metro queue ABNORMALLY LOW.", t: 520 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 760 },
      { agent: "dispatcher", level: "think", text: "Pattern signature matches: localized perimeter obstruction, not crowd-wide surge.", t: 1180 },
      { agent: "dispatcher", level: "think", text: "Required actions touch life-safety envelope · severity = RED.", t: 1600 },
      { agent: "dispatcher", level: "alert", text: "Severity=RED — gating broadcast pending Auditor clearance.", t: 1940 },
      { agent: "dispatcher", level: "info", text: "Escalating → Risk Auditor Node [gemini-2.5-pro]", t: 2220 },
      { agent: "auditor", level: "info", text: "Auditor node online · 5-point safety verification initiated.", t: 2520 },
      { agent: "auditor", level: "think", text: "Check 1/5 · density crush-risk model → mitigated projection 0.71 ✓", t: 2880 },
      { agent: "auditor", level: "think", text: "Check 2/5 · Gate-03 soft-close envelope 60s > 45s min ✓", t: 3220 },
      { agent: "auditor", level: "think", text: "Check 3/5 · E-Ring counter-flow vector — no collision ✓", t: 3560 },
      { agent: "auditor", level: "think", text: "Check 4/5 · PA script panic-term scan — 0 flagged ✓", t: 3900 },
      { agent: "auditor", level: "think", text: "Check 5/5 · medical pre-position vs BCCI SOP ✓", t: 4240 },
      { agent: "auditor", level: "ok", text: "auditor_clearance = TRUE · releasing payload to Broadcast Layer.", t: 4580 },
      { agent: "broadcast", level: "alert", text: "Map: G3 → RED · Concourse N/W → RED · adjacent zones ORANGE.", t: 4880 },
      { agent: "broadcast", level: "info", text: "Mobile push staged · 38,200 devices · PA broadcast armed.", t: 5160 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 5.2s end-to-end · auditor cleared.", t: 5440 },
    ],
  },
  medical_emergency: {
    id: "SCENARIO_06",
    key: "medical_emergency",
    name: "Cardiac Event · Stand B / Sec 12",
    short: "Medical",
    timestamp: "21:30",
    match_status: "ACTIVE_PLAY_OVER_27",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 70,
      gate_03_turnstile_rate_per_min: 80,
      gate_05_turnstile_rate_per_min: 65,
      concourse_b_density_index: 0.62,
      metro_station_queue_length_meters: 25,
    },
    expected_severity: "ORANGE",
    zone_state: {
      g1: "orange", g2: "green", g3: "green", g4: "green", g5: "green",
      concourse_n: "green", concourse_s: "orange",
      concourse_e: "green", concourse_w: "green",
      metro: "green",
    },
    payload: {
      severity_level: "ORANGE",
      reasoning_justification:
        "Wearable telemetry from Stand-B / Seat S12-R-22 reports flatline cardiac rhythm. Adjacent steward beacon confirms collapsed patron. Life-critical but locally contained — dispatch Bay-02 medics via cleared C-Ring, open Gate-01 ambulance lane, page Manipal Hospital cardiac team, and run a discreet PA. No crowd-wide redirect required.",
      mitigation_directives: [
        { target_zone: "Medical Bay 02 → Stand B / Sec 12", action_required: "DISPATCH 2 PARAMEDICS + AED · ROUTE VIA C-RING",
          priority: "IMMEDIATE", action: { kind: "dispatch_medics", label: "DISPATCH MEDICS", eta_s: 90 } },
        { target_zone: "Gate 01 Ambulance Lane", action_required: "OPEN PRIORITY LANE · CLEAR BOLLARDS",
          priority: "IMMEDIATE", action: { kind: "open_gate", label: "OPEN LANE", eta_s: 45 } },
        { target_zone: "Manipal Hospital · Cardiac ER", action_required: "PAGE CARDIAC TEAM · BED 4 STANDBY",
          priority: "IMMEDIATE", action: { kind: "page_hospital", label: "PAGE HOSPITAL", eta_s: 30 } },
        { target_zone: "Stand B Public Address", action_required: "DISCRETE PA: 'Doctor needed in Stand B'",
          priority: "IMMEDIATE", action: { kind: "broadcast_pa", label: "BROADCAST", eta_s: 5 } },
        { target_zone: "Adjacent Steward Team", action_required: "CROWD-SCREEN AROUND PATIENT · PRESERVE DIGNITY",
          priority: "DEFERRED", action: { kind: "deploy_security", label: "DEPLOY 4", eta_s: 60 } },
      ],
      pa_system_announcement_script:
        "Will the team doctor please report to Stand B, Section 12. Thank you.\n\n[KN] ತಂಡದ ವೈದ್ಯರು ದಯವಿಟ್ಟು ಸ್ಟ್ಯಾಂಡ್ ಬಿ, ವಿಭಾಗ 12ಕ್ಕೆ ತಲುಪಿ. ಧನ್ಯವಾದಗಳು.",
      mobile_push_notification_text:
        "Medical response active in Stand B. Please stay seated so paramedics can pass.",
    },
    trace: [
      { agent: "sensor", level: "alert", text: "Wearable telemetry · seat S12-R-22 · cardiac rhythm flatline detected.", t: 0 },
      { agent: "sensor", level: "info", text: "Steward beacon B-12-04 confirms collapsed patron · age est. 60s.", t: 320 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 580 },
      { agent: "dispatcher", level: "think", text: "Life-critical · locally contained · severity ORANGE with IMMEDIATE actions.", t: 940 },
      { agent: "dispatcher", level: "think", text: "Optimal medic route: Bay-02 → C-Ring (clear) · ETA 90s · 1.4× faster than direct.", t: 1340 },
      { agent: "dispatcher", level: "emit", text: "Structured payload emitted · severity=ORANGE · directives=5", t: 1740 },
      { agent: "broadcast", level: "info", text: "Map: Concourse-S amber · Gate-01 amber (ambulance lane).", t: 2020 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 2.3s · agent auto-executing IMMEDIATE directives.", t: 2280 },
    ],
  },

  pitch_invasion: {
    id: "SCENARIO_07",
    key: "pitch_invasion",
    name: "Pitch Invasion · Fan Crosses Boundary",
    short: "Pitch Invasion",
    timestamp: "22:10",
    match_status: "OVER_43_RCB_BAT",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 50,
      gate_03_turnstile_rate_per_min: 60,
      gate_05_turnstile_rate_per_min: 45,
      concourse_b_density_index: 0.58,
      metro_station_queue_length_meters: 20,
    },
    expected_severity: "ORANGE",
    zone_state: {
      g1: "green", g2: "green", g3: "green", g4: "green", g5: "green",
      concourse_n: "orange", concourse_s: "green",
      concourse_e: "green", concourse_w: "green",
      metro: "green",
    },
    payload: {
      severity_level: "ORANGE",
      reasoning_justification:
        "Boundary-rope CV breach: single subject vault from Stand C / Sec 4 onto pitch at long-on. Player safety primary — deploy 4 security for intercept, signal umpires to halt play, cut broadcast to crowd shot under BCCI § 12, and ML-trace the seat origin for post-event ban processing.",
      mitigation_directives: [
        { target_zone: "Pitch Boundary · Long-on", action_required: "DEPLOY 4 SECURITY · SUBJECT INTERCEPT",
          priority: "IMMEDIATE", action: { kind: "deploy_security", label: "DEPLOY 4", eta_s: 18 } },
        { target_zone: "Umpire On-Field Radio", action_required: "SIGNAL HALT PLAY · DEAD-BALL CONFIRMED",
          priority: "IMMEDIATE", action: { kind: "halt_play", label: "HALT PLAY", eta_s: 3 } },
        { target_zone: "Broadcast Truck (BCCI Live)", action_required: "CAMERA CUT-AWAY · CROWD SHOT NO-FOLLOW",
          priority: "IMMEDIATE", action: { kind: "camera_cutaway", label: "CUT FEED", eta_s: 2 } },
        { target_zone: "ML Vision · Stand C / Sec 4", action_required: "TRACE SEAT ORIGIN · LIFE BAN LOG",
          priority: "DEFERRED", action: { kind: "trace_identify", label: "ML TRACE", eta_s: 30 } },
        { target_zone: "Stand C Public Address", action_required: "REMINDER: BOUNDARY = INSTANT EJECTION + BAN",
          priority: "DEFERRED", action: { kind: "broadcast_pa", label: "BROADCAST", eta_s: 8 } },
      ],
      pa_system_announcement_script:
        "Patrons are reminded that entering the field of play is a criminal offence under the Karnataka Police Act, punishable by a lifetime ban from BCCI venues.\n\n[KN] ಮೈದಾನ ಪ್ರವೇಶ ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಕಾಯಿದೆಯಡಿ ಅಪರಾಧ. ಬಿಸಿಸಿಐ ಸ್ಥಳಗಳಿಂದ ಜೀವಮಾನ ನಿಷೇಧ ಶಿಕ್ಷೆ.",
      mobile_push_notification_text:
        "Pitch invasion in progress. Please stay seated. Play will resume shortly.",
    },
    trace: [
      { agent: "sensor", level: "alert", text: "Boundary-rope CV trigger · single subject vault at long-on (cam 7).", t: 0 },
      { agent: "sensor", level: "info", text: "Origin estimate: Stand C / Sec 4 / Row 8 (parallax ±2 seats).", t: 320 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 580 },
      { agent: "dispatcher", level: "think", text: "Player safety primary · severity ORANGE · 5 directives + camera policy.", t: 940 },
      { agent: "dispatcher", level: "think", text: "BCCI broadcast clause § 12 · cut-away mandatory · enforce no-follow.", t: 1300 },
      { agent: "dispatcher", level: "emit", text: "Structured payload emitted · severity=ORANGE · directives=5", t: 1660 },
      { agent: "broadcast", level: "info", text: "Map: Concourse-N amber · stand C flagged for review.", t: 1940 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 2.2s · agent auto-executing on-field directives.", t: 2200 },
    ],
  },

  hostile_breach: {
    id: "SCENARIO_08",
    key: "hostile_breach",
    name: "Suspect Package · Gate 04 K9 Alert",
    short: "Hostile Breach",
    timestamp: "19:45",
    match_status: "PRE_MATCH_GATES_OPEN",
    current_rainfall_mm: 0.0,
    sensor_metrics: {
      gate_01_turnstile_rate_per_min: 110,
      gate_03_turnstile_rate_per_min: 95,
      gate_05_turnstile_rate_per_min: 130,
      concourse_b_density_index: 0.48,
      metro_station_queue_length_meters: 80,
    },
    expected_severity: "RED",
    zone_state: {
      g1: "green", g2: "green", g3: "orange", g4: "red", g5: "green",
      concourse_n: "orange", concourse_s: "red",
      concourse_e: "red", concourse_w: "green",
      metro: "green",
    },
    payload: {
      severity_level: "RED",
      reasoning_justification:
        "K9 unit positive alert + portable EDTD reading 0.18 ppm at Gate-04 baggage lane 2 (threshold 0.05 ppm). Unattended package, owner unidentified. Treat as credible threat under SOP § 8.1: 100m perimeter evacuation, seal G4, dispatch State Police Bomb Squad, notify CRPF + Disaster Management. PA must use covert wording — explicit panic terms forbidden.",
      mitigation_directives: [
        { target_zone: "Bengaluru State Police · Bomb Squad", action_required: "DISPATCH BOMB SQUAD · ETA 11 MIN",
          priority: "IMMEDIATE", action: { kind: "dispatch_bomb_squad", label: "DISPATCH SQUAD", eta_s: 660 } },
        { target_zone: "Gate 04 + 100m Perimeter", action_required: "EVACUATE PERIMETER · REVERSE INBOUND FLOW",
          priority: "IMMEDIATE", action: { kind: "evacuate_perimeter", label: "EVACUATE", eta_s: 120 } },
        { target_zone: "Gate 04 Turnstiles", action_required: "SEAL G4 · NO INGRESS OR EGRESS",
          priority: "IMMEDIATE", action: { kind: "seal_gate", label: "SEAL G4", eta_s: 15 } },
        { target_zone: "Gates 01 / 03 / 05", action_required: "REROUTE ALL G4 INBOUND TO 01/03/05",
          priority: "IMMEDIATE", action: { kind: "reroute_flow", label: "REROUTE", eta_s: 20 } },
        { target_zone: "CRPF + Bengaluru DM", action_required: "NOTIFY · OPEN BI-DIRECTIONAL CHANNEL",
          priority: "IMMEDIATE", action: { kind: "notify_authority", label: "NOTIFY", eta_s: 12 } },
        { target_zone: "PA System · COVERT", action_required: "ANNOUNCE 'TECHNICAL CHECK AT G4' · NO PANIC TERMS",
          priority: "IMMEDIATE", action: { kind: "broadcast_pa", label: "BROADCAST", eta_s: 6 } },
        { target_zone: "Media Box", action_required: "EMBARGO INCIDENT · DESIGNATE PIO SPOKESPERSON",
          priority: "DEFERRED", action: { kind: "notify_authority", label: "EMBARGO", eta_s: 45 } },
      ],
      pa_system_announcement_script:
        "Attention please. Gate 4 is temporarily unavailable for a technical check. Please use Gates 1, 3 or 5 for entry. Thank you for your cooperation.\n\n[KN] ಗಮನಿಸಿ. ಗೇಟ್ 4 ತಾತ್ಕಾಲಿಕವಾಗಿ ಬಂದ್ ಆಗಿದೆ. ದಯವಿಟ್ಟು ಗೇಟ್ 1, 3 ಅಥವಾ 5 ಬಳಸಿ.",
      mobile_push_notification_text:
        "Gate 4 temporarily unavailable. Please enter via Gate 1, 3 or 5. Thank you.",
    },
    auditor: {
      verdict: "CLEARED",
      checks: [
        { label: "Hostile-incursion SOP § 8.1 alignment", result: "Covert PA language confirmed · 0 panic terms detected" },
        { label: "100m perimeter capacity vs evacuee count", result: "Buffer absorbs 2,400 evacuees · within Gate-03 staging margin" },
        { label: "Bomb Squad ETA + holding pattern feasibility", result: "11 min ETA · 12 min holding capacity at sealed G4 · APPROVED" },
        { label: "Inter-agency channel handshake", result: "CRPF channel BLR-OPS-9 acked · DM channel KAR-DM-1 acked" },
        { label: "Media embargo + PIO assignment", result: "Embargo armed · Sr. PIO designated · single point of comms" },
      ],
      clearance: true,
    },
    trace: [
      { agent: "sensor", level: "alert", text: "K9 unit ALPHA-3 positive alert · Gate-04 baggage screening lane 2.", t: 0 },
      { agent: "sensor", level: "alert", text: "Portable EDTD reading 0.18ppm · threshold 0.05ppm · 3.6× over.", t: 320 },
      { agent: "sensor", level: "info", text: "Handoff → Dispatcher Agent [gemini-2.5-flash]", t: 620 },
      { agent: "dispatcher", level: "alert", text: "Credible threat profile · severity=RED · 7 directives required.", t: 1020 },
      { agent: "dispatcher", level: "alert", text: "SOP § 8.1 mandates covert PA · explicit terms forbidden.", t: 1380 },
      { agent: "dispatcher", level: "info", text: "Escalating → Risk Auditor Node [gemini-2.5-pro]", t: 1700 },
      { agent: "auditor", level: "info", text: "Auditor node online · 5-point hostile-incursion verification.", t: 2000 },
      { agent: "auditor", level: "think", text: "Check 1/5 · SOP § 8.1 covert PA alignment ✓", t: 2380 },
      { agent: "auditor", level: "think", text: "Check 2/5 · 100m perimeter capacity 2,400 evacuees ✓", t: 2740 },
      { agent: "auditor", level: "think", text: "Check 3/5 · bomb squad ETA 11min vs holding 12min ✓", t: 3100 },
      { agent: "auditor", level: "think", text: "Check 4/5 · CRPF + DM channel handshakes ✓", t: 3460 },
      { agent: "auditor", level: "think", text: "Check 5/5 · media embargo + PIO designation ✓", t: 3820 },
      { agent: "auditor", level: "ok", text: "auditor_clearance = TRUE · releasing payload.", t: 4180 },
      { agent: "broadcast", level: "alert", text: "Map: G4 RED · Concourse S+E RED · perimeter armed.", t: 4480 },
      { agent: "broadcast", level: "info", text: "Push staged · 18,400 devices · covert language verified.", t: 4760 },
      { agent: "broadcast", level: "ok", text: "Cycle complete · 5.0s · auditor cleared · executing on-field directives.", t: 5040 },
    ],
  },

};
